version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eris
    versions:
    - 0.14.0
